# Generated by Django 4.0.4 on 2022-05-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='numero_cuenta',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rnc',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
